docs/benchmarking_docker.md

Getting started is missing .md extension

Getting started is missing .md extension

---

src/Microsoft.Crank.Controller/Ignore/IgnoreRule.cs

Matches full segments when no * is set.

Fixing gitgnore resolution

---

src/Microsoft.Crank.Controller/JobConnection.cs

Display log urls

---

src/Microsoft.Crank.Controller/JobConnection.cs
src/Microsoft.Crank.Controller/README.md

Fixing globing pattern

---

src/Microsoft.Crank.Agent/Startup.cs

Adding option to set agent build path

---

src/Microsoft.Crank.Jobs.Bombardier/Program.cs
src/Microsoft.Crank.Jobs.Wrk/Program.cs
src/Microsoft.Crank.Jobs.Wrk/WrkProcess.cs
src/Microsoft.Crank.Jobs.Wrk2/Program.cs

Returning correct status code in client jobs

---

src/Microsoft.Crank.Controller/Program.cs

Display error log if available

---

src/Microsoft.Crank.Agent/Startup.cs

Add ability to specify max build timeout

---

src/Microsoft.Crank.Agent/Startup.cs

Updating dotnet-install location

---

src/Microsoft.Crank.Agent/Startup.cs

Outputting build errors

---

src/Microsoft.Crank.Jobs.Bombardier/Program.cs

Updating bombardier binaries, including ARM

---

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
src/Microsoft.Crank.Agent/JobsApis.cs
src/Microsoft.Crank.Agent/Repository/InMemoryJobRepository.cs
src/Microsoft.Crank.Agent/Startup.cs

- Skip MVC for most apis that are used to poll jobs, which could impact the current runs
- Removing locks and use ConcurrentDictionary

Optimizing polling apis

---

src/Microsoft.Crank.Agent/GZipFileResult.cs
src/Microsoft.Crank.Controller/JobConnection.cs
src/Microsoft.Crank.Controller/WebUtils.cs

Just to make remote workers happy
@davidfowl @adamsitnik @roji

Display trace file download progress

---

src/Microsoft.Crank.Agent/Startup.cs

Make AOT4Mono compatible for both x64 and arm64

---

src/Microsoft.Crank.Agent/JobContext.cs
src/Microsoft.Crank.Agent/Startup.cs

Dispose event pipe session after the source is stopped

---

src/Microsoft.Crank.Controller/Program.cs

- Variables can use templates. They are evaluated first.
- Imports are merged on local configurations in order to change an imported property locally. e.g. default transport for bombardier

Apply templates to variables

---

src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Models/Job.cs

Add configurable collect timeout

---

src/Microsoft.Crank.Agent/Startup.cs

Fix reuseSource and reuseBuild for docker files

---

src/Microsoft.Crank.Controller/Ignore/IgnoreFile.cs

Fix gitignore discovery

---

src/Microsoft.Crank.AzureDevOpsWorker/Program.cs
src/Microsoft.Crank.Controller/WebUtils.cs

The tool could downloading traces from a CI and break
Fixes #254

Handle non-interactive mode

---

src/Microsoft.Crank.Controller/ExcludeOptions.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Controller/results.json
test/Microsoft.Crank.IntegrationTests/HelloTests.cs

Implement exclude option

---

src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj
src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Jobs.Bombardier/Program.cs
src/Microsoft.Crank.Jobs.HttpClient/Program.cs
src/Microsoft.Crank.Jobs.PipeliningClient/Program.cs
src/Microsoft.Crank.Jobs.Wrk/WrkProcess.cs
src/Microsoft.Crank.Jobs.Wrk2/Program.cs
src/Microsoft.Crank.Models/Job.cs
test/Microsoft.Crank.IntegrationTests/CommonTests.cs
test/Microsoft.Crank.IntegrationTests/HelloTests.cs
test/Microsoft.Crank.IntegrationTests/assets/multiclient.benchmarks.yml

Fix multi-client metadata

---

src/Microsoft.Crank.Controller/JobConnection.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Controller/results.json
src/Microsoft.Crank.Models/Job.cs

Download files globing pattern

---

NOTICE.txt
src/Microsoft.Crank.Agent/Git.cs
src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj
src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/Documentation.cs
src/Microsoft.Crank.Controller/JobResults.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Models/Dependency.cs
src/Microsoft.Crank.Models/Job.cs

Saving dependencies information

---

src/Microsoft.Crank.Controller/ExecutionResult.cs
src/Microsoft.Crank.Controller/JobSerializer.cs
src/Microsoft.Crank.Controller/ResultComparer.cs
src/Microsoft.Crank.Models/JobResults.cs
src/Microsoft.Crank.RegressionBot/Microsoft.Crank.RegressionBot.csproj
src/Microsoft.Crank.RegressionBot/Models/DependencyChange.cs
src/Microsoft.Crank.RegressionBot/Models/Regression.cs
src/Microsoft.Crank.RegressionBot/Program.cs
test/Microsoft.Crank.RegressionBot.Tests/Microsoft.Crank.RegressionBot.Tests.csproj
test/Microsoft.Crank.RegressionBot.Tests/TemplateTests.cs
test/Microsoft.Crank.RegressionBot.Tests/assets/benchmarkresult1.json
test/Microsoft.Crank.RegressionBot.Tests/assets/benchmarkresult2.json
test/Microsoft.Crank.RegressionBot.Tests/assets/template.fluid

This will not impact existing templates, but deploying this will allow to start updating them.

Generate dependency changes in regression bot

---

src/Microsoft.Crank.Jobs.HttpClient/Program.cs
src/Microsoft.Crank.Jobs.HttpClient/WorkerResult.cs
src/Microsoft.Crank.Jobs.Wrk/WrkProcess.cs

Generate multiple key for the same measurement.
This is the continuation of a previous change that added support for these multi-key measurements in the controller.

Continuation of metrics refactoring

---

src/Microsoft.Crank.Agent/JobContext.cs
src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Models/Job.cs

Implement custom interval measurement

---

src/Microsoft.Crank.Controller/ExcludeOptions.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md

Add possibility to exclude high and low results

---

src/Microsoft.Crank.Agent/Startup.cs

Kill job when driver is closed during trace collection

---

src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Models/Job.cs

Improve error reporting

---

src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
test/Microsoft.Crank.IntegrationTests/CommonTests.cs

Fix iterations results

---

src/Microsoft.Crank.Jobs.Wrk/wrk.yml
src/Microsoft.Crank.Jobs.Wrk2/wrk2.yml

serverPath is not used in wrk and wrk2 configuration

chore: adjust wrk parameters

---

src/Microsoft.Crank.PullRequestBot/Program.cs

Fix the Pull Request bot's schema pointing to the Regression bot.

Fix schema path

---

src/Microsoft.Crank.PullRequestBot/Program.cs

Fix linux support

---

src/Microsoft.Crank.Agent/Startup.cs

Fixes https://github.com/aspnet/Benchmarks/issues/1720

Disable rollForward

---

src/Microsoft.Crank.Controller/Documentation.cs
src/Microsoft.Crank.Controller/JobConnection.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Models/Job.cs

Not a big fan of `DownloadOutputOutput` but I tried to keep naming consistent

Add job options to download output and build logs

---

src/Microsoft.Crank.Controller/ExecutionResult.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/ResultComparer.cs
src/Microsoft.Crank.Models/JobResults.cs

This PR is a draft of adding the ability for the crank controller to produce a comparison report for BenchmarkDotNet results that can be used with the `crank-pr` tool (see #399).
At the moment this draft uses some code taken from [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) and [Perfolizer](https://github.com/AndreyAkinshin/perfolizer) and trimmed down to just the parts that are needed in order to handle unit conversions and rounding to improve the UX compared to rendering everything as nanoseconds and bytes using the raw values from the JSON output. It would be preferable to just reference BenchmarkDotNet itself, but I've left out adding the additional dependency to do that for now.
Example JSON files I've been using to test are included below, which give the following …

Support comparing BenchmarkDotNet results

---

src/Microsoft.Crank.PullRequestBot/Configuration.cs
src/Microsoft.Crank.PullRequestBot/Program.cs

A single build is performed for base or head when multiple benchmarks or profiles are provided.

Batch base and pr runs

---

src/Microsoft.Crank.Agent/Startup.cs

File format has changed for https://aka.ms/dotnet/7.0.1xx/daily/productCommit-win-x64.txt
https://github.com/dotnet/installer/pull/13132

React to new SDK version format

---

src/Microsoft.Crank.Agent/Startup.cs

Measure cpustats when limits are sets

---

src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj

Update mono posix package

---

docker/agent/run.sh

Otherwise, there are no limits! Option available since Docker 1.8.

Limit docker logs

---

src/Microsoft.Crank.Agent/Startup.cs

@martincostello @BrennanConroy

Fix 7.0 preview packages discovery

---

azure-pipelines.yml

> We think the RoslynTools.MSBuild package is mucked up
Matt Mitchell

Disable signing validation

---

src/Microsoft.Crank.Agent/Startup.cs

Retry SDK installs

---

azure-pipelines.yml

Reverts dotnet/crank#503
https://github.com/dotnet/arcade/issues/11724#issuecomment-1334580279

Revert "Disable signing validation"

---

src/Microsoft.Crank.Agent/Startup.cs

based on the upstream change: https://github.com/dotnet/installer/pull/15036

update productCommit file parsing

---

src/Microsoft.Crank.Agent/Startup.cs

Recording both actual publish size (same as today) and symbols size individually.

Record symbols size

---

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/JobConnection.cs
src/Microsoft.Crank.Controller/README.md

Instead of single individual files using gzip.

Send output files as a single zip

---

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
src/Microsoft.Crank.Controller/JobConnection.cs

Improves reliability on slow networks.

Introduce custom network constants 

---

src/Microsoft.Crank.Controller/Program.cs

Fix NullReferenceException when no profiles are provided

---

eng/Version.Details.xml
eng/common/cross/build-rootfs.sh
eng/common/generate-locproject.ps1
eng/common/templates/job/job.yml
eng/common/templates/variables/pool-providers.yml
global.json

Revert "[main] Update dependencies from dotnet/arcade"

---

src/Microsoft.Crank.Jobs.H2Load/Program.cs

Fix first request measurement and rps counter name

---

src/Microsoft.Crank.Jobs.H2Load/Program.cs
src/Microsoft.Crank.Jobs.H2Load/h2load.yml

Makes it easier to swap between bombardier and h2load

Add bodyFile option to h2load

---

NOTICE.txt
eng/Signing.props
src/Microsoft.Crank.Controller/Microsoft.Crank.Controller.csproj
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.PullRequestBot/Microsoft.Crank.PullRequestBot.csproj
src/Microsoft.Crank.PullRequestBot/Program.cs
src/Microsoft.Crank.RegressionBot/Microsoft.Crank.RegressionBot.csproj
src/Microsoft.Crank.RegressionBot/Program.cs

For #345 , use **JsonSchema.Net** to replace **Manatee.Json**.

Remove Manatee.Json dependency

---

src/Microsoft.Crank.Agent/Startup.cs

fix benchmark fail when perfview download fails

---

docker/agent/Dockerfile

fixed #556 
--------------
After build a new docker image, run a sample to test it. It seems ok.
crank-agent 
```
./build.sh --url http://*:5010
docker logs -f crank-agent
```
output
crank
modify the `hello.benchmarks.yml` to add `collect: true`
```
crank --config ./samples/hello/hello.benchmarks.yml --scenario hello --profile local
```
output

[Dockerfile] update perfcollect setup

---

src/Microsoft.Crank.Agent/Startup.cs

timestamps store in UTC when saving results to JSON

---

src/Microsoft.Crank.Agent/Startup.cs

Replace Environment.ProcessorCount when cpuSet is defined.

---

src/Microsoft.Crank.RegressionBot/regressionbot.schema.json

/cc @catcherwong 
I haven't found why yet ... but that seems to fix the validation

Fix regression bot json schema validation

---

src/Microsoft.Crank.PullRequestBot/Program.cs

Some results are not added as comments, investigating the reason.

Adding more logs to PR benchmarks

---

src/Microsoft.Crank.Controller/JobConnection.cs
test/Microsoft.Crank.IntegrationTests/CommonTests.cs

buildFiles options support urls

---

src/Microsoft.Crank.Controller/Program.cs

remove one IsRepeatOver in SpanShouldKeepJobRunning

---

src/Microsoft.Crank.Jobs.HttpClient/Microsoft.Crank.Jobs.HttpClient.csproj
src/Microsoft.Crank.Jobs.HttpClient/Program.cs
src/Microsoft.Crank.Jobs.HttpClient/Timeline.cs
src/Microsoft.Crank.Jobs.HttpClient/TimelineFactory.cs

- Method argument
- Base64 encoded body
- Content headers

Add options to support grpc requests

---

src/Microsoft.Crank.Jobs.HttpClient/httpclient.yml
src/Microsoft.Crank.Jobs.PipeliningClient/pipelining.yml

Will default to the csproj's one.

Remove explicit tfms from clients

---

src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/Documentation.cs
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Models/Source.cs

Fixes #587 
Fixes #588 
Example:
```yaml
jobs:
redis:
source:
dockerPull: redis
readyStateText: Ready to accept connections
```

Add docker pull support

---

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
src/Microsoft.Crank.Agent/Startup.cs

fix stop job unstable

---

src/Microsoft.Crank.Jobs.Bombardier/Program.cs
src/Microsoft.Crank.Jobs.HttpClient/Program.cs
src/Microsoft.Crank.Jobs.Wrk/WrkProcess.cs
src/Microsoft.Crank.Jobs.Wrk2/Program.cs
src/Microsoft.Crank.PullRequestBot/Program.cs

Fixes slow benchmarks that fail on the first request

Improve first request measurement resiliency

---

eng/dependencies.props
src/Microsoft.Crank.Controller/Microsoft.Crank.Controller.csproj
src/Microsoft.Crank.RegressionBot/Microsoft.Crank.RegressionBot.csproj

Fixes component governance warnings for System.Drawing.Common

Update Microsoft.Data.SqlClient version

---

src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.Controller/README.md
src/Microsoft.Crank.Controller/VariableParser.cs
test/Microsoft.Crank.IntegrationTests/CommonTests.cs
test/Microsoft.Crank.IntegrationTests/assets/hello.benchmarks.yml

fix #567 
Added a new option `--variable-json` for typed variables.

Support typed variables on the command line

---

src/Microsoft.Crank.Controller/ResultComparer.cs

compare omit benchmark results

---

src/Microsoft.Crank.Jobs.Bombardier/Program.cs
src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

closed #621 
```ps1
crank --config .\local.benchmarks.yml --profile local --scenario hello `
--variable "stream=true" `
--variable "body={'a':1}"  `
--variable "certFile=https://github.com/aspnet/Benchmarks/blob/main/docker/nginx/testCert.crt?raw=true" `
--variable "keyFile=https://github.com/aspnet/Benchmarks/blob/main/docker/nginx/testCert.rsa?raw=true"  `
--variable "verb=POST"
```
Agent output

Add remaining Bombardier arguments

---

src/Microsoft.Crank.Controller/Program.cs

Ensure empty arguments are encoded as double quotes

---

src/Microsoft.Crank.Controller/ResultComparer.cs

fix IndexOutOfRangeException when compare single benchmark with same full name

---

src/Microsoft.Crank.Agent/Startup.cs

Downloads SDK and runtimes from 9.0 feeds when `--application.framework net9.0` is used. The TFM is the csproj is kept to net8.0 since net9.0 doesn't exist already. But net9.0 is detected and uses the new feeds.

Add support for net9.0

---

src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Agent/WindowsLimiter.cs

add support for windows CpuLimitRatio

---

eng/dependencies.props
src/Microsoft.Crank.RegressionBot/Microsoft.Crank.RegressionBot.csproj

* Updating the SqlClient version wasn't enough

[Component governance] Update Azure.Identity dependency

---

src/Microsoft.Crank.Agent/Startup.cs

Remove some hard coded environment variables which should be set in config files instead.

Remove some ENVs

---

src/Microsoft.Crank.Agent/Startup.cs

This uses `/LogFile:` which is the documented way to run perfview without user interaction. If the process fails to start then the log file content is returned to the user. Tested with wrong perfview arguments:
```
[05:57:41.252] 'application' is now building ... http://localhost:5010/jobs/1/buildlog
[05:58:00.451] 'application' failed on agent, stopping...
PerfView logging started at 11/20/2023 5:57:59 PM
Error: The value 'GCHeapAndTypeName' for parameter ClrEvents is not a member of the enumeration Keywords.
The legal values are either a decimal integer, 0x and a hex integer or
None
GC
GCHandle
Binder
Loader
Jit
NGen
StartEnumeration
StopEnumeration
Security
...
```
/cc @Maoni0 @markples

Detect perfview failures

---

src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.JobOjectWrapper/Program.cs
src/Microsoft.Crank.Models/Job.cs

This fixes all counters collection including CPU when running with cpuset on windows.

Fix JobObjectWrapper detection

---

docker/agent/Dockerfile

libmsquic updated commands
python3 tools

Update Dockerfile for .net8.0

---

src/Microsoft.Crank.Agent/Startup.cs

Don't use process after disposal

---

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Models/Job.cs

Allows jobs to send measurements to the host agent.

Set current job url as ENV

---

src/Microsoft.Crank.Agent/Startup.cs

json files are generated since https://github.com/dotnet/installer/commit/445175df6d3473a0a3a930db7176b5548dc9465c.

switch to product commit json

---

src/Microsoft.Crank.Agent/Startup.cs

Fixes https://github.com/dotnet/crank/issues/710

Fix version resolution

---

eng/dependencies.props
src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj
src/Microsoft.Crank.Agent/Startup.cs
src/Microsoft.Crank.Controller/Microsoft.Crank.Controller.csproj
src/Microsoft.Crank.Controller/Program.cs
src/Microsoft.Crank.PullRequestBot/Program.cs

Update use of hash algorithms

---

src/Microsoft.Crank.Agent/Startup.cs

Handle invalid cpuset and cpulimitratio

---

src/Microsoft.Crank.Agent/Startup.cs

https://github.com/dotnet/sdk/pull/41316

use "sdk" in ResolveSdkVersion

---

Directory.Packages.props

Update Azure.Identity from 1.11.3 -> 1.11.4.

Update Azure.Identity from 1.11.3 -> 1.11.4.

---

src/Microsoft.Crank.Agent/Startup.cs

Fixes https://github.com/dotnet/crank/issues/756

Refactor CurrentVersions and cache file downloads

---

Directory.Packages.props

Should fix CG alerts by taking the specific version into account.

Use Transitive pinning

---

src/Microsoft.Crank.Jobs.HttpClient/Program.cs

forgot to change the check for `measturingStart` in `if` statement https://github.com/dotnet/crank/pull/786

fix measuringStart check in httpClient

---

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
src/Microsoft.Crank.Agent/ProcessUtil.cs
src/Microsoft.Crank.Controller/JobSerializer.cs
src/Microsoft.Crank.Controller/Program.cs

preventing from injecting malicious code by JobsController/download
preventing from injecting malicious code by JobSerializer - using env. variable table name

preventing from injecting malicious code by JobsController/download

---

azure-pipelines-release.yml

Reorder the NuGet push commands to work with NuGet properly.

Reorder the nuget push commands to work with NuGet properly.

---

azure-pipelines-release.yml

Use the correct env for the nuget key.

Use the correct env for the nuget key.

---

src/Microsoft.Crank.Agent/Startup.cs

https://github.com/dotnet/runtime/blob/2cb402c6eb169fa875a9b4875bedc4a82a5e28a2/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs#L265

Add UpDownCounter support
