dotnet/crank

src/Microsoft.Crank.Controller/Program.cs
in some scenarios where for example a build was not performed (using binaries)
there are metadata emitted without corresponding metrics, causing aggregation failures
when run on multiple machines
=> metric aggregation fails if metadata not emitted

src/Microsoft.Crank.Agent/Startup.cs
For the following configuration, `GetAssemblyName` fails to locate the csproj file:
```
jobs:
server:
source:
repository: https://github.com/MyRepo
branchOrCommit: my-branch
project: src/MyFolder/MyProject.csproj
```
According to the logs, it tries to find the csproj file at `.../MyRepo/MyProject.csproj`, fails to do that, and proceeds without extracting the assembly name. This fix resolved the issue for me, so `.../MyRepo/src/MyFolder/MyProject.csproj` is properly located.
Please note very similar code at:
- https://github.com/dotnet/crank/blob/e2b8f3c58f3b2dcecf05cb4fa6d622ba2b88ca8f/src/Microsoft.Crank.Agent/Startup.cs#L2597
- https://github.com/dotnet/crank/blob/e2b8f3c58f3b2dcecf05cb4fa6d622ba2b88ca8f/src/Microsoft.Crank.Agent/Startup.cs#L2641
I'm not certain they should be fixed as …
=> Fix project file path

src/Microsoft.Crank.Jobs.Bombardier/Program.cs, src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
After filing issue #81 I did some research to see if I can figure out why it wasn't working. Turns out it was indeed missing support for running this on Mac OS. Since I'm on a Mac I figured I might as well fix it myself.
I've rewritten the OS detection logic a little bit, because it seemed to be using some old API that doesn't accurately report the difference between Mac en Linux, which was needed in this case. Because of the security features in OSX I also had to run an additional command `spctl --add <executable>` to allow the downloaded executable to be run. Interestingly it asks me for permission to run the tool, but in the mean time it just runs it. But I guess that's an OSX issue.
=> Add support for running Bombardier job on Mac OS

src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
This logic is copied verbatim from wrk.yml: 
https://github.com/dotnet/crank/blob/caf293d98ac2b438b6c77dcb54b72c6d9cc67f3e/src/Microsoft.Crank.Jobs.Wrk/wrk.yml#L33
https://github.com/aspnet/Benchmarks/pull/1587 will depend on this.
=> Add serverScheme support to bombardier.yml

src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.Models/Job.cs, src/Microsoft.Crank.Models/JobState.cs
Collection was stopped when the application was stopped normally. The driver is expecting the application to stop in 30s and huge traces would put it in timeout.
The bug is that collection should not stop when Stopping is invoked in a normal path. The driver is supposed to call Stopping then TraceCollecting.
=> Fixing trace collection when jobs are stopped

src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.Controller/JobConnection.cs, src/Microsoft.Crank.Controller/Program.cs, src/Microsoft.Crank.Controller/README.md, src/Microsoft.Crank.Controller/VersionChecker.cs, src/Microsoft.Crank.Models/Job.cs, src/Microsoft.Crank.Models/Source.cs
Example: The application's source can be reused, so it's not cloned again. The load's build files can be reused, so it's not built again.
```
crank --config ..\..\samples\hello\hello.benchmarks.yml --scenario hello --profile local --application.options.reuseSource true --load.options.reuseBuild true
```
When a source parameter is changed, like a branch, or a project name, the source will still be cloned as the source key will change too. 
It doesn't detect the latest commit on a branch though. It could be done automatically by adding it to the computed SourceKey We could also add a custom "VaryBy" property to refresh the source for instance every day, or per user, ...
=> Reuse source or builds between benchmarks

docs/event_counters.md
I had some issues following the docs for collecting System.Runtime counters. Specifically, using `--application.counterProviders System.Runtime` as recommended resulted in the error `Could not find part of the configuration path: '[application.counterProviders, System.Runtime]'`
After digging around a bit, I noticed this should actually be `application.options.counterProviders`
This PR is just a quick fix for the documentation.
=> Fix documentation for collecting event counters

src/Microsoft.Crank.Agent/ProcessUtil.cs
This seems to fix the issue I was seeing where the output of `cmd /c npm list` was truncated.  There might be other ways to fix this, or other locations to call `WaitForExit()`, but I think this is the smallest possible change that fixes the issue.
=> [ProcessUtil] Ensure output buffers are flushed before exit

src/Microsoft.Crank.Controller/default.config.yml
See https://github.com/dotnet/diagnostics/pull/2139 for more details about this counter.
=> Added the gc-committed counter

src/Microsoft.Crank.Agent/Startup.cs
`EventPipeSession.Stop` needs to be called for the tracing session to successfully receive rundown events. 
In addition, counter sessions don't need rundown so we should specify requestRundown to false while starting the counter session to avoid unnecessary cost of emitting rundown.
=> Call Stop on tracing EventPipeSessions

src/Microsoft.Crank.Agent/Startup.cs
This adds both uncompressed and compressed (for wire size) metrics.
New output from application build:
| application                |         |
| -------------------------- | ------- |
| CPU Usage (%)              | 0       |
| Cores usage (%)            | 0       |
| Working Set (MB)           | 16      |
| Build Time (ms)            | 13,581  |
| Start Time (ms)            | 422     |
| Published Size (KB)        | 238,996 |
| Compressed Image Size (KB) | 94,880  |
=> Add container size metrics

NuGet.config
These are unnecessary and confuse the nuget security analysis task.
=> Remove blob feeds

src/Microsoft.Crank.Agent/CompositeRelayServer.cs, src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.Controller/Program.cs, src/Microsoft.Crank.Controller/README.md
When `--relay-enable-http` is set, the agent will listen to both the HTTP port and Azure Relay connection for jobs.
Fixes #325
=> Support hybrid connections

docs/local_application.md
Hi,
I noticed a small mistake while reading the "Benchmarking local applications" documentation.
The change made in the `Main` method of the program is not taken into account with the given command since the YAML benchmark file used is the one which fetches source from a GitHub repo. It should be the YAML file already used throughout the page (i.e. `sample/local/local.benchmarks.yml`).
Regards
=> [Doc] Fixed the crank command in "Testing local changes"

docs/microbenchmarks.md, samples/micro/dotnet.benchmarks.yml, samples/micro/micro.benchmarks.yml
Hi,
I stumbled upon an issue while reading and testing the "Running micro-benchmarks" section of the documentation.
In the example below (from the `micro.benchmarks.yml` sample), the `job` variable does not expand as expected (we expect `short`) at runtime, and thus results in a error from BenchmarkDotNet (it fails parsing its arguments).
```yaml
benchmarks:
source:
localFolder: .
project: micro.csproj
variables:
filter: "*"
job: short
arguments: --job {{job}} --filter {{filter}} --memory
options:
benchmarkDotNet: true
```
Here is the output from `crank-agent` (shrinked) : 
```
[11:07:27.276]   Arguments:  --inProcess --cli C:\Users\[...]\src\published\micro.exe --join --exporters briefjson markdown --job {
"DriverVersion": 0,
"ServerVersion": 4,
"Id": 0,
[...]
"Dependencies": [], …
```
=> [Doc/Samples] Rename variables in microbenchmarks YAML samples to avoid conflict

src/Microsoft.Crank.Agent/Startup.cs
On Linux, if the app isn't build by the agent, the execution bit on the target executable isn't set. 
The easiest solution if to set it all the time before launching the process.
=> On Linux, make sure we can run the executable (set the execution bit)

src/Microsoft.Crank.Controller/Configuration.cs, src/Microsoft.Crank.Controller/Program.cs, src/Microsoft.Crank.RegressionBot/Configuration.cs
Fixes #342
Here is how profiles and configs can be rewritten. Note that the current syntax still works.
```yml
imports:
- https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
jobs:
server:
source:
repository: https://github.com/dotnet/crank
branchOrCommit: main
project: samples/hello/hello.csproj
readyStateText: Application started.
scenarios:
hello:
application:
job: server
agent: main # the agent to deploy the service on (optional)
load:
job: bombardier
variables:
serverPort: 5000
path: /
profiles:
local:
variables:
serverAddress: localhost
agents: # new name for "jobs" (optional change)
main:
aliases: 
- application # matches a service name without specific agent (optional)
endpoints: 
- http://localhost:5010
secondary:
aliases: 
- load …
```
=> Add support for agent mappings

src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj, src/Microsoft.Crank.Agent/README.md, src/Microsoft.Crank.Agent/Startup.cs
We can't run Crank.Agent as a windows service.
This PR adds an opt-in parameter to let Crank.Agent be windows-service compatible.
=> Adds support for running CrankAgent as a windows service

src/Microsoft.Crank.Agent/Startup.cs
When counters are started too early in can block the app completely on Linux. Example with Platform benchmarks.
=> Wait until application is ready to start counters

src/Microsoft.Crank.Controller/Configuration.cs, src/Microsoft.Crank.Controller/Program.cs, src/Microsoft.Crank.Models/JobResults.cs
Example:
```yaml
results: # creates results from measurements
- name: runtime-counter/alloc-rate/p90
measurement: runtime-counter/alloc-rate
description: 90th Allocation Rate (B/sec)
format: n0
aggregate: percentile90
reduce: sum
- name: alloc-per-request
description: Allocations Per request (B/req)
format: n2
onResultsCreated:
- |
var allocations = benchmarks.jobs.application.results["runtime-counter/alloc-rate/p90"]
var rps = benchmarks.jobs.load.results["http/rps/mean"];
benchmarks.jobs.application.results["alloc-per-request"] = allocations / rps;
```
=> Execute scripts after results are available

src/Microsoft.Crank.Jobs.Bombardier/Program.cs
This PR fixes the calculation of the total request number, the number of 3xx requests was duplicated (see below)
https://github.com/dotnet/crank/blob/4484a3418314f991528ba6e2a8797f2d2396a1b0/src/Microsoft.Crank.Jobs.Bombardier/Program.cs#L233-L240
The bug is not present for Wrk and Wrk2 as the total number of requests is parsed from the standard output.
=> [BUGFIX] Bombardier job: remove duplicate req3xx in the requests number sum

src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml, src/Microsoft.Crank.Jobs.Wrk/wrk.yml, src/Microsoft.Crank.Jobs.Wrk2/wrk2.yml
Fixes #356
As suggested in #356, this PR adds support for the `--timeout` option that Bombardier, wrk and wrk2 support out of the box. 
Bombardier has a default timeout of 2s (thus the default value of 2 in the YAML file), while wrk and wrk2 do not have a default value (thus the empty default values in their respective YAML files, the `--timeout` option is passed only when it is not empty with a Fluid conditional expression).
This has been tested with the `hello` example and it works well:
```
[04:55:19.277] > wrk -d 15s -c 256 http://localhost:5000/ --latency --timeout 2s -t 32
[04:55:19.326] Processing job 'load' (2) in state Running
[04:55:20.345] Processing job 'application' (1) in state Running
[04:55:21.371] Processing job 'load' (2) in state Running
[...]
[04:57:01.897] > wrk2  -d …
```
=> Add a timeout option for Bombardier, wrk and wrk2 jobs

NOTICE.txt, eng/Signing.props, src/Microsoft.Crank.Agent/Controllers/JobsController.cs, src/Microsoft.Crank.Agent/Dumper.cs, src/Microsoft.Crank.Agent/Git.cs, src/Microsoft.Crank.Agent/Log.cs, src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj, src/Microsoft.Crank.Agent/ProcessUtil.cs, src/Microsoft.Crank.Agent/Startup.cs
As discussed in https://github.com/dotnet/crank/pull/365, this PR adds log file support for crank agent.
Users can pass an opt-in `--log-path` command-line argument with a full path to a log-file.
Log files roll every 1 day.
=> Adds Crank.Agent log file support - serilog

src/Microsoft.Crank.Controller/Program.cs
Since version `0.2.0-alpha.22071.1` of Microsoft.Crank.Controller on [NuGet](https://www.nuget.org/packages/Microsoft.Crank.Controller/0.2.0-alpha.22071.1), I experience an issue when using the `--table` option of `crank`:
```
Unhandled exception. System.InvalidOperationException: Multiple options with name "table" found. This is usually due to nested options.
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.FindOption(String name, Func`2 by)
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
at …
```
=> [BUGFIX] Critical: fix duplication of the `--table` option

src/Microsoft.Crank.Agent/Startup.cs, test/Microsoft.Crank.IntegrationTests/AgentFixture.cs, test/Microsoft.Crank.IntegrationTests/CommonTests.cs
Two fixes here:
1. The agent will output `Agent ready` even tough it may fail to start (fails to bind the port for example). Instead of calling `host.RunAsync()`, wait explicitely that `host.StartAsync()` was completed before starting the logic to process jobs
2. In test, when the agent failed to start there was no log displayed. Instead of throwing an error in `AgentFixture`, I check that the agent was started successfully in the test constructor, flushing the agent logs if necessary
=> Do not output "Agent ready" when it's not ready yet

src/Microsoft.Crank.PullRequestBot/BotOptions.cs, src/Microsoft.Crank.PullRequestBot/CredentialsHelper.cs, src/Microsoft.Crank.PullRequestBot/Program.cs
Support the use of GitHub Enterprise instances via a new `--github-base-url` parameter, which configures the Octokit client to use a different base address for API calls.
=> Support GitHub Enterprise

src/Microsoft.Crank.PullRequestBot/README.md
Add the new `--github-base-url` flag from #403 to the README for `crank-pr`.
=> Add --github-base-url to README

src/Microsoft.Crank.Jobs.Bombardier/Program.cs
This is mostly useful when running Bombardier client on local machine where the output should be human readable.
=> Add ability to get output as plain-text

src/Microsoft.Crank.Agent/Startup.cs
Fix the following error:
```
[05:39:52.842] 'application' failed on agent, stopping...
An unexpected error occurred while building the job: One or more errors occurred. (Directory not empty : '/tmp/benchmarks-agent/benchmarks-server-1/dotnet-mono')
```
=> Delete folder recursively

src/Microsoft.Crank.Controller/WebUtils.cs
- 4K is too small so use 64K instead
Future: We can also use 2 buffers to do a faster download. You can read with the second buffer while the first one is in use from the previous write.
=> Use a bigger buffer for downloads

src/Microsoft.Crank.Controller/Program.cs
Because of a network error, I had a run fail with the message:
```
Configuration '/mnt/c/git/dd-trace-dotnet/tracer/build/crank/https:/raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml' could not be loaded.
```
which is incredibly confusing, and had me waste a few minutes to understand why Crank was apparently trying to convert the URL into a path.
This PR fixes the logic to resolve the path in the error message only if it isn't an URL.
=> Don't resolve configuration path if it's an url

docker/agent/Dockerfile
MsQuic v2+ is incompatible with MsQuic v1.
.NET 6 needs MsQuic 1.8/1.9, while .NET 7 already depends on MsQuic 2+, so both versions have to be installed on the machine.
Unfortunately, we don't have a signed package for MsQuic 2.0 yet, so the workaround is to build it from sources (we do the same in our CI).
I verified the agent in local docker, that HTTP/3 benchmarks would run on both .NET 6 and latest .NET 7.
cc @ManickaP
=> Update msquic on linux for .NET 6 and .NET 7

src/Microsoft.Crank.RegressionBot/Program.cs
This changes `Change` to mean the delta between the current result and the one before it.
The issue filer uses this value when filing issues.
@sebastienros
=> Fix Regression.Change to be current - previous

src/Microsoft.Crank.PullRequestBot/CredentialsHelper.cs, src/Microsoft.Crank.PullRequestBot/Program.cs
- Invoke the script host the correct way for the executing OS.
- Use the specified `--github-base-url` value, if any, when getting GitHub credentials.
Resolves #400.
=> Fix crank-pr on non-Windows

src/Microsoft.Crank.Agent/Startup.cs
Do not log an error if `EventPipeEventSource` tries to read the network stream after it's disposed of.
Looks like there's the possibility of a race between stopping the source and the network stream being disposed of that causes an `ObjectDisposedException` to be thrown and logged when shutting things down.
It seems benign to me, so it just isn't logged now. I had a look at the code and I couldn't spot an obvious way that the code that was incorrect that could have been changed to not have the exception happen at all in the first place, but I might just not have fully understood the code's flow.
An excerpt from some logs where I spotted this are below.
```sh
[08:43:23 INF] Driver stopping job '4'
[08:43:24 INF] Processing job 'load' (4) in state Stopped
[08:43:24 INF] Job 'load' (4) has …
```
=> Handle EventPipeEventSource being disposed

src/Microsoft.Crank.PullRequestBot/Program.cs
With this change only the profiles/benchmarks/components that are available in the configuration file will be used. The goal is to be able to create as many configuration file as there are components/profiles compatible combinations and have different pipelines use each file.
Example:
For the runtime repository benchmarks can target windows/linux and x64/arm64. The idea is to create 4 files, each of them will have the scripts required for a shell/arch couple, and the profiles it supports.
Running a benchmark with "coreclr aspnet-arm-lin plaintext" will then only work for the configuration file that contains the arm/lin commands, using bash as the shell and targeting linux.
If a command contains "coreclr aspnet-arm-lin,aspnet-arm-win plaintext" then one pipeline will be able to run the lin …
=> Add support for multiple pipelines

src/Microsoft.Crank.Agent/Startup.cs
Update the agent to support determining .NET 7 versions from the public release notes.
It might be the case that this can't be merged until 7.0.0 RTM as it would interfere with your own testing before that ships, but without these changes I can't get an app targeting .NET 7 RC1 to work correctly because it tries to use the daily builds feed and then fails to get the right version numbers automatically.
=> Fix support for .NET 7 public releases

src/Microsoft.Crank.PullRequestBot/Configuration.cs, src/Microsoft.Crank.PullRequestBot/Microsoft.Crank.PullRequestBot.csproj, src/Microsoft.Crank.PullRequestBot/Program.cs, src/Microsoft.Crank.PullRequestBot/pullrequestbot.schema.json
Allows to use templates in PullRequestBot configs in all Crank arguments (`defaults`, `benchmark.arguments`, `profile.arguments`, `component.arguments`, command-line passed `arguments`)
Example of config with templates:
```yml
components:
runtime:
....
arguments: '--{{job}}.options.outputFiles ..\runtime\artifacts\tests\coreclr\windows.x64.Release\tests\Core_Root\'
defaults: '--{{job}}.framework net7.0'
variables:
job: client
benchmarks:
json:
description: TechEmpower JSON Scenario - ASP.NET Platform implementation
arguments: --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/platform.benchmarks.yml --scenario plaintext
variables:
job: application
http-client-get8k-h1:
description: HttpClient GET 8K - HTTP/1.1
arguments: --config …
```
=> Apply Fluid templates to PullRequestBot configs

src/Microsoft.Crank.PullRequestBot/Program.cs, src/Microsoft.Crank.PullRequestBot/README.md
Add support for cloning private repositories and public repositories in GitHub Enterprise Server when an access token is specified.
Resolves #462.
Replaces #473.
=> Support cloning repos from GitHub Enterprise Server in PR Bot

src/Microsoft.Crank.PullRequestBot/Command.cs, src/Microsoft.Crank.PullRequestBot/Program.cs
Similar to crank-pr `--arguments` option, but from PR comment.
PR comment would look like:
`/benchmark microbenchmarks aspnet-citrine-win runtime --variable filter=System.Memory*`
=> Treat remaining PR comment text as Crank arguments

docs/post_processing.md
This change is being made based on the following from a recent run with `crank`.
`[01:46:21.591] WARNING: '--output' has been deprecated, in the future please use '--json'.`
=> Update flag to use

src/Microsoft.Crank.PullRequestBot/BotOptions.cs, src/Microsoft.Crank.PullRequestBot/ProcessUtil.cs, src/Microsoft.Crank.PullRequestBot/Program.cs, src/Microsoft.Crank.PullRequestBot/README.md
- Add pre-check for crank command (run without component arguments), cancel build on pre-check failure
- Fix process termination in `ProcessUtil`
- Add retries when running crank (except for crank compare) -- on non-zero exit code
- Add crank logs to console without waiting (stop capturing output in `StringWriter`, except for crank compare)
- Add `--external-log-uri` parameter to pass the logs link, add the link to start comment
- Add arguments from /benchmark comment to start comment
- Update PR bot help comment
Contributes to https://github.com/dotnet/runtime/issues/77215
cc @sebastienros @kunalspathak
=> Add precheck, retries and parameter to pass link to logs to PR bot

src/Microsoft.Crank.Controller/default.config.yml
There was a copy-paste error where percentile75 and percentile50 were using `90` for the percentiles.
cc @sebastienros @mitchdenny
=> Fix percentiles

src/Microsoft.Crank.PullRequestBot/Program.cs
Fixes cloning commands on Windows for long paths
c.f. https://github.com/dotnet/runtime/pull/79778
=> Add support for long paths on windows

src/Microsoft.Crank.Controller/Ignore/IgnoreFile.cs, src/Microsoft.Crank.Controller/Ignore/IgnoreRule.cs, src/Microsoft.Crank.Controller/JobConnection.cs, test/Microsoft.Crank.IntegrationTests/GitIgnoreTests.cs, test/Microsoft.Crank.IntegrationTests/SkipOnMacOsAttribute.cs, test/Microsoft.Crank.IntegrationTests/SkipOnWindowsAttribute.cs
Found a bug while working on a local folder benchmark: `/obj` would be uploaded disregarding the `[Oo]bj/` rule, so implemented some tests based on the spec https://git-scm.com/docs/gitignore and fixed other issues.
=> Improve .gitignore support

src/Microsoft.Crank.RegressionBot/Program.cs, src/Microsoft.Crank.RegressionBot/Queries.cs
- DateTime is not indexed and filtering on it might result to timeouts
- Prevent SQL injections from configuration
=> Optimize SQL query performance

docker/agent/Dockerfile
Build is currently broken, using package instead since they are now available.
=> Update msquic setup support in docker file

src/Microsoft.Crank.Jobs.H2Load/Program.cs
Output is aggregated on the same content after the first request run. This means the "parse output" step will find the results from the first run instead of the second one.
=> [h2load] Reset Output before actual load

src/Microsoft.Crank.Agent/Controllers/JobsController.cs, src/Microsoft.Crank.Controller/Documentation.cs, src/Microsoft.Crank.Controller/JobConnection.cs, src/Microsoft.Crank.Controller/README.md, test/Microsoft.Crank.IntegrationTests/CommonTests.cs
Necessary to download files from the csproj folder or `obj/,...`
=> Allow project relative file downloads

src/Microsoft.Crank.Jobs.H2Load/Program.cs, src/Microsoft.Crank.Jobs.H2Load/h2load.yml
This PR switches h2load to the header format used by bombardier - `key: value` instead of `key=value`.
[Proxies runs](https://dev.azure.com/dnceng/internal/_build/results?buildId=2121723&view=logs&j=0d02efdf-002e-5960-fff9-d39f49e676e1&t=e0f008ef-8e2e-5503-fdc6-88c09c6b8cc3&l=35) for h2 are failing after https://github.com/aspnet/Benchmarks/pull/1798
```console
-c 28 -t 28 -m 100 -d 15 -w 5 -n 0 -u  https://10.0.0.102:8080/?s=100  -p h2c --header "Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7" --header "Connection: keep-alive"
```
```
Header: Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q
[STDERR] Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
[STDERR]    at …
```
=> Match 'name: value' header format in h2load wrapper

src/Microsoft.Crank.Controller/Program.cs
For #485 , fix the help information of `crank compare`
=> Fix crank subcommand help information

src/Microsoft.Crank.Controller/Program.cs
=> Update DefaultBenchmarkDotNetArguments to avoid cli path with spaces.

src/Microsoft.Crank.Controller/JobConnection.cs, test/Microsoft.Crank.IntegrationTests/CommonTests.cs
fixed #282 
------
Using the following command to test
```
crank --config .\samples\local\local.benchmarks.yml --scenario hello --profile local --application.options.downloadFiles App_Data/logs/*.* 
```
Before modification
After modification
=> Fix duplicate folder name when use downloadFiles options

src/Microsoft.Crank.PullRequestBot/Program.cs
It was not initialized when running the bot so all thumbprints were identical.
=> Fix thumbprint initialization

docker/agent/Dockerfile
Installing MsQuic 2+ over 1.9 (like it was before) removed old packages, so I have to hack installation to have both available.
Installation verified by running .NET 6 and .NET 7 apps querying Quic.IsSupported on the updated docker image
Also, any issues with MsQuic installation should not affect other crank users, so the failures will be ignored
cc @sebastienros
=> Update MsQuic to 2.2.1 and fix MsQuic 1.9

src/Microsoft.Crank.Controller/default.config.yml
Values are between [0-1] and represent a percentage. This currently displays `0` as formatted with `n0`. With `p0` this will show up as `36%`. 
NB: There is another counter that returns percentages (Max Time in GC), but this one returns values in [0-100] range.
=> Use % format for GC Heap Fragmentation

global.json
Attempting to fix this signing validation error:
```
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.23370.3\tools\SdkTasks\SigningValidation.proj : error : Version 8.0.100-preview.6.23330.14 of the .NET SDK requires at least version 17.6.0 of MSBuild. The current available version of MSBuild is 17.4.0.51802. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.23370.3\tools\SdkTasks\SigningValidation.proj : error : The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.23370.3\tools\SdkTasks\SigningValidation.proj : …
```
=> Update dotnet versions

src/Microsoft.Crank.RegressionBot/Program.cs
I believe the fact that the YAML doesn't contain labels/owners here could be the reason of an NRE.
https://github.com/aspnet/Benchmarks/blob/7b44db144e31b4fd0fc648315713ada14a09ccb5/build/regressions.config.yml#L134
=> Fix potential NRE when yaml file is incomplete

src/Microsoft.Crank.Agent/Startup.cs
Small hashes in urls may collide and GH can't generate the diff in these cases.
=> Increase stored hash to prevent collisions

src/Microsoft.Crank.Controller/Program.cs
Actually fixes #628.
I completely missed that I forgot to put the actual double quotes in. Tested this time and it's working.
=> Ensure empty arguments are encoded as double quotes (correctly)

docker/agent/Dockerfile
Installing latest package from packages.microsoft.com (.NET 8 bumped required version to 2.2.2+).
We dropped QUIC support from .NET 6, so I removed msquic 1.9.
Fixes https://github.com/aspnet/Benchmarks/issues/1894
cc @sebastienros
=> Update msquic to latest published package

src/Microsoft.Crank.Agent/Startup.cs
Noticed the CTRL+C was exiting its boundaries sometimes and killing the Agent too. This is restoring the CTRL handlers in a finally block and changing the handler group to 0.
=> Improve CTRL+C reliability

src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.Controller/Program.cs, src/Microsoft.Crank.Models/Job.cs, src/Microsoft.Crank.Models/Source.cs
Still doing some testing on this, but from initial testing this seems to work and builds will be reused as long as all the build inputs (see BuildKeyData) are identical.
=> Fix NoBuild support

eng/common/templates/job/publish-build-assets.yml, eng/common/templates/post-build/common-variables.yml, eng/common/templates/post-build/post-build.yml
Matching PR: https://github.com/dotnet/arcade/pull/11577
=> Remove cross-org build step

src/Microsoft.Crank.Agent/Startup.cs
This is the responsibility of the benchmark
=> Don't override default Thread_AssignCpuGroups value

src/Microsoft.Crank.Agent/Controllers/JobsController.cs
```
[02:43:55.502] Uploading C:\Users\mirogers.REDMOND\AppData\Local\Temp\tmpB997.tmp (334,718KB)
[02:44:20.668] Could not ping the agent on 'asp-perf-lin:5001', retrying ...
[02:44:25.807] Could not ping the agent on 'asp-perf-lin:5001', retrying ...
[02:44:30.931] Could not ping the agent on 'asp-perf-lin:5001', retrying ...
Unhandled exception. System.InvalidOperationException: An error occurred while uploading a file.
---> System.Net.Http.HttpRequestException: Error while copying content to a stream.
---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
```
=> Keep controller connection alive while uploading files

src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.JobOjectWrapper/Program.cs, test/Microsoft.Crank.IntegrationTests/CommonTests.cs, test/Microsoft.Crank.IntegrationTests/SkipOnLinuxAttribute.cs
Instead of relying on starting in the correct working directory, specify that we want the Microsoft.Crank.JobObjectWrapper.exe in the same location of the assembly/tool.
=> Call Microsoft.Crank.JobObjectWrapper.exe with full path 

src/Microsoft.Crank.Agent/Startup.cs
Use `<RestoreAdditionalProjectSources/>` in csproj to link to nightly build feeds since the root NuGet.config might be invalidated by local NuGet.config `<clear />` statements.
=> Inject updated list of feeds in csproj files

docker/agent/Dockerfile
Older version breaks curl (and git) in current image.
=> Fix h2 support in Dockerfile

src/Microsoft.Crank.Jobs.HttpClient/Program.cs
LatencyMeanMs is not taking into consideration the parallelism nature of the load test.
The calculation is currently done by taking the whole time it took to run the test and divide it by the number of requests which implies that the requests were done sequentially
=> HttpClient: Fixed LatencyMeanMs not calculating properly

samples/hello/hello.benchmarks.yml, samples/hello/hello.csproj
Closes #682 
Updating new target framework for sample project 3.1 is outdated now.
Impact may not be so much technically but if someone have to learn from this tutorial https://www.youtube.com/watch?v=2IgfrnG-128&t=692s , there will be no need for 3.1 (outdated version) to be added in system anymore.
=> Updating target framework for hello sample

src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.Agent/WindowsLimiter.cs, src/Microsoft.Crank.JobOjectWrapper/Program.cs
`JobObjectWrapper` is not necessary anymore, tested locally. We might still benefit from using a SUSPENDED thread once the API is available in the runtime.
`Environment.ProcessorCount` is also returning the correct value, and overriding its value is not necesary anymore.
=> Use SetProcessAffinityMask instead of SetProcessDefaultCpuSets

src/Microsoft.Crank.Jobs.K6/Program.cs, src/Microsoft.Crank.Jobs.K6/scripts/default.js
Results:
```
| load                    |                    |
| ----------------------- | ------------------ |
| Max CPU Usage (%)       | 12                 |
| Max Cores usage (%)     | 348                |
| Max Working Set (MB)    | 209                |
| Max Private Memory (MB) | 236                |
| Build Time (ms)         | 3,340              |
| Start Time (ms)         | 85                 |
| Published Size (KB)     | 72,944             |
| Symbols Size (KB)       | 0                  |
| .NET Core SDK Version   | 8.0.101            |
| ASP.NET Core Version    | 8.0.1+8e941eb42f81 |
| .NET Runtime Version    | 8.0.1+bf5e279d9239 |
| First Request (ms)      | 109                |
| Requests                | 70,513             |
| Bad responses           | 0                  |
| …
```
=> Track more latencies in K6

src/Microsoft.Crank.Agent/Microsoft.Crank.Agent.csproj, src/Microsoft.Crank.Agent/Startup.cs, src/Microsoft.Crank.EventSources/BenchmarksEventSource.cs
Related to: https://github.com/aspnet/Benchmarks/pull/1862#issuecomment-1925110806
- Added the startup event as a part of the Benchmarks event source.
- Tested with the hello scenario using the following command: ```crank --config /crank/samples/local/local.benchmarks.yml --scenario hello --profile local --application.collect true --application.collectArguments "Providers=Benchmarks"``` 
- Observed the event showing up in the Events View in PerfView:
Please let me know if there is a better way to accomplish this.
=> Added the Startup Event to the Benchmarks Event Source

src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml, src/Microsoft.Crank.Jobs.H2Load/h2load.yml, src/Microsoft.Crank.Jobs.HttpClient/httpclient.yml, src/Microsoft.Crank.Jobs.K6/k6.yml, src/Microsoft.Crank.Jobs.PipeliningClient/pipelining.yml, src/Microsoft.Crank.Jobs.Wrk/wrk.yml, src/Microsoft.Crank.Jobs.Wrk2/wrk2.yml
Reverts the jobs that are defined inside this repo to use `source` instead of `sources`. In my recent change ([link](https://github.com/dotnet/crank/commit/ec795589deff97bac339962928499fe4446986b0?diff=unified&w=0)), I made it so that all the jobs such as wrk, bombardier, wrk2 etc. used `sources` instead of `source`. This commit also included a bug fix which is required for this change to work or it would throw an error. Anyone using a crank controller which does not have the bug fix yet will get the following error:
$ crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml --scenario plaintext --profile aspnet-perf-lin
The service 'load' is missing some properties to start the job.
Check that any of these properties is set: project, …
=> Revert jobs to use source instead of sources

docs/README.md, docs/measurements.md, samples/post/Program.cs, samples/post/post.csproj, src/Microsoft.Crank.Agent/Controllers/JobsController.cs, test/Microsoft.Crank.IntegrationTests/CommonTests.cs, test/Microsoft.Crank.IntegrationTests/Microsoft.Crank.IntegrationTests.csproj, test/Microsoft.Crank.IntegrationTests/assets/post.benchmarks.yml
When .NET can't be used it might be easier to invoke a web api instead of formatting json and writing it on the console.
=> Add measurements api

docs/getting_started.md
I was experimenting in AWS Graviton, followed the [steps](https://github.com/dotnet/crank/blob/main/docs/getting_started.md) and ran into below issue. Resolved in local, thought of updating here to set the expectations.
```
An unexpected error occurred while building the job. System.AggregateException: One or more errors occurred. 
(An error occurred trying to start process 'git' with working directory
'/tmp/benchmarks-agent/benchmarks-server-4362/nuy4a4bz.dvx/crank'. No such file or directory)
```
=> doc update for git

azure-pipelines.yml, azure-pr-pipelines.yml
This splits out the current yml AzDO definition into an internal and pr file.
The internal runs have also been configured to use the new internal templates and use the other 1ES approved steps and jobs.
The new public yml has not been tested yet, as I can't create a new pipeline from a yml file just in a branch.
=> 1ES Pipelines

azure-pipelines.yml
Remove -pt from pool image names as the images have been removed. Transition started here: https://github.com/dotnet/dnceng/issues/2081 and finished ~2 weeks ago.
=> Remove -pt from pool image names as they have been removed.

src/Microsoft.Crank.Agent/Startup.cs
This PR implements the functionality of copying files to a docker container. Changes required to the current implementation include to create, copy the attached files and then start rather than simply running the container.
One caveat here was that the destination path should be the folder name where the files must go rather than the path to the files themselves (CC: @sebastienros). For example:
``crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/containers.benchmarks.yml --scenario json_aspnet_current --profile local --profile noload --application.options.outputFiles "./docs/development.md;app/development.md"`` 
doesn't work as it leads to the filename as: app\development.md\development.md
Also, quotations around the source;[destination] are necessary …
=> Copy Files to Docker

src/Microsoft.Crank.Jobs.Bombardier/Program.cs
fix #747 
**test for `-b`** 
```yml
load:
job: bombardier
variables:
serverPort: 5000
path: /
verb: POST
body: '{\"name\":\"World\"}'
```
**test for delete local file**
Should I write a test for this scenario?
=> fix bombardier miss -b and delete local file

src/Microsoft.Crank.Controller/ResultComparer.cs, src/Microsoft.Crank.Models/JobResults.cs
Fix `JsonSerializationException` if a BenchmarkDotNet benchmark does not generate any results due to an error.
Excerpt from the really long error log where I found this:
```console
Method    | Job          | Arguments                   | Toolchain              | input    | Mean         | Error        | StdDev     | Gen0     | Gen1     | Gen2     | Allocated  |
---------- |------------- |---------------------------- |----------------------- |--------- |-------------:|-------------:|-----------:|---------:|---------:|---------:|-----------:|
Solve2015 | AdventOfCode | /p:UseArtifactsOutput=false | Default                | Y2015-01 |     11.89 μs |     3.004 μs |   0.165 μs |   0.0153 |        - |        - |    1.38 KB |
Solve2015 | ShortRun     | Default                     | …
```
=> Fix JsonSerializationException

src/Microsoft.Crank.Agent/Startup.cs
Remove now-redundant condition for .NET 9.
I was trying to run crank for a .NET 9 application and got this error:
```
[10:38:35 INF] Patching project file '/tmp/benchmarks-agent/benchmarks-server-2278/quz1y0ad.4mq/src/API/API.csproj'
[10:38:35 INF] Runtime:  (Current)
[10:38:35 INF] SDK:  (Current)
[10:38:35 INF] ASP.NET:  (Current)
[10:38:35 INF] Patching existing global.json file
[10:38:35 INF] An unexpected error occurred while building the job. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Crank.Agent.Startup.CloneRestoreAndBuild(String path, Job job, String dotnetHome, CancellationToken cancellationToken) in …
```
=> Remove redundant condition for NET 9

src/Microsoft.Crank.Agent/Startup.cs
VB/C# Compiler runs with ServerGC and impacts some benchmark latencies.
=> Shut down MSBuild server after builds

src/Microsoft.Crank.Controller/ResultComparer.cs
Fix `NullReferenceException` if a benchmark produces no results.
The problem was previously masked before the change I made in #753.
```console
BenchmarkDotNet v0.14.0, Ubuntu 22.04.4 LTS (Jammy Jellyfish)
AMD EPYC 7763, 1 CPU, 4 logical and 2 physical cores
.NET SDK 9.0.100-rc.1.24452.12
[Host] : .NET 9.0.0 (9.0.24.43107), X64 RyuJIT AVX2
Job=ShortRun  Toolchain=InProcessEmitToolchain  IterationCount=3  
LaunchCount=1  WarmupCount=3  
Method    | input    | Mean         | Error        | StdDev    | Gen0     | Gen1     | Gen2     | Allocated  |
---------- |--------- |-------------:|-------------:|----------:|---------:|---------:|---------:|-----------:|
Solve2015 | Y2015-01 |     11.71 μs |     2.001 μs |  0.110 μs |   0.0153 |        - |        - |    1.38 KB |
Solve2015 | Y2015-02 | …
```
=> Fix NullReferenceException

docker/agent/run.sh
Current syntax doesn't work, and the valid one is ugly and creates a subshell for each comment:
```
--someoption `# some comment` \
```
=> Fix run script comment's location

Directory.Packages.props
This update is required to resolve a component governance alert
=> Update MessagePack to 2.5.187

src/Microsoft.Crank.Controller/Documentation.cs, src/Microsoft.Crank.Controller/README.md
I tried to include the `beforeScript` in one of automatically set benchmarks, and it did not work with argument `--application.options.beforeScript "..."` because part of configuration path was not found:
>
crank --config https://raw.githubusercontent.com/DeagleGross/Benchmarks/refs/heads/dmkorolev/tls-httpsys-fixes/scenarios/tls.benchmarks.yml --scenario mTls-handshakes-httpsys --profile aspnet-perf-win --application.framework net10.0 --application.options.beforeScript "cmd.exe /c dir"
`Could not find part of the configuration path: '[application.options.beforeScript, cmd.exe /c dir]'`
However, `--application.beforeScript` worked:
> crank --config https://raw.githubusercontent.com/DeagleGross/Benchmarks/refs/heads/dmkorolev/tls-httpsys-fixes/scenarios/tls.benchmarks.yml --scenario …
=> fix: specify proper cmd arg for `beforeScript`, `afterScript` commands

src/Microsoft.Crank.Jobs.HttpClient/Program.cs, src/Microsoft.Crank.Jobs.HttpClient/httpclient.yml
Adding an option to explicitly set the sslProtocol version to use on `SocketsHttpHandler`
=> feat: support SslProtocol parameter for httpClient job

src/Microsoft.Crank.Agent/Startup.cs
Some servers ignore the If-Modified-Since header and return 200.
=> Handle non-304 response when checking urls

docker/agent/Dockerfile
verified by running `./build.sh` on wsl and then ran the container. Unfortunately, it is not available in the main distribution (maybe i did not find it correctly http://ftp.debian.org/debian/).
If you want, I can change base image from `mcr.microsoft.com/dotnet/sdk:8.0` to `mcr.microsoft.com/dotnet/sdk:8.0-alpine` like is done in [TLS benchmarks](https://github.com/aspnet/Benchmarks/blob/3773f786bb25e1f344370be398a91bf236cf3f07/src/BenchmarksApps/TLS/Kestrel/Dockerfile#L2) which provides easier way to install latest openssl version.
=> feat: update crank-agents to install latest openssl

src/Microsoft.Crank.Agent/MachineCounters/MachineCountersEventSource.cs, src/Microsoft.Crank.Agent/MachineCounters/OS/LinuxMachineCpuUsageEmitter.cs, src/Microsoft.Crank.Agent/ProcessUtil.cs, src/Microsoft.Crank.Agent/Startup.cs
On linux cpu collection emitting was working only for the first run due to disposal of singleton `MachineCountersEventSource.Log`.
I removed `_eventSource?.Dispose();` invocation, and adjusted logging a bit.
=> fix: dont dispose machine-counters eventsource for linux cpu stats collection

azure-pipelines-release.yml
Creates a release yaml for Crank. This is the first pass using the automated template provided to use by 1ES. The tasks mostly match what we had in the previous manual release steps with the primary difference being a dryrun option and the path of the PackageArtifacts. The current most pressing question is whether the pool is setup properly and to run a test dry-run.
=> Create Crank Release Yaml

src/Microsoft.Crank.Agent/MachineCounters/MachineCountersController.cs, src/Microsoft.Crank.Agent/MachineCounters/OS/IMachinePerformanceCounterEmitter.cs, src/Microsoft.Crank.Agent/MachineCounters/OS/LinuxMachineCpuUsageEmitter.cs, src/Microsoft.Crank.Agent/MachineCounters/OS/WindowsMachineCpuUsageEmitter.cs, src/Microsoft.Crank.Agent/MachineCounters/OS/WindowsProcessCpuTimeEmitter.cs, src/Microsoft.Crank.Agent/Measurements.cs, src/Microsoft.Crank.Controller/Documentation.cs, src/Microsoft.Crank.Controller/README.md, src/Microsoft.Crank.Models/Job.cs
Added option `--job.processesCpuToCollect` (multi-option) to collect cpu stats for the specific processes. Supported OS is Windows only (so far).
example:
> --config "D:\code\crank\samples\local\local.benchmarks.yml" --scenario hello --profile local --application.processesCpuToCollect "**lsass**" --application.processesCpuToCollect "**taskmgr**"
gives the output with additional 2 stats:
=> feat: add support for custom processes cpu collection

azure-pipelines-release.yml
Clean-up and finish the release yaml. This consisted of properly setting the pool to use, updating how the NuGetApiKey is passed in, and putting the publish step itself behind having to be run from main.
Test run with the dryrun features still included, but that shows variables are set properly and packages loaded: https://dev.azure.com/dnceng/internal/_build/results?buildId=2641796&view=results
Final test run with the main branch filter: https://dev.azure.com/dnceng/internal/_build/results?buildId=2642486&view=results. It correctly did not do the actual publish.
=> Clean-up and finish the release yaml

docker/agent/Dockerfile
Current 3.4.0-2 version is failing
=> Use floating version for openssl

docker/agent/Dockerfile
I would like to collect linux perfCollect dump and see the openssl symbols. Therefore using not "testing" but "sid" (unstable) repo and [openssl-dbgsym](https://packages.debian.org/sid/openssl-dbgsym)
=> feat: add openssl-dbgsym installation for perf collections

src/Microsoft.Crank.Agent/Startup.cs
It appears, that non-admin rights is enough to run scripts.
Moreover, we cant run `afterScript` in admin mode, because also passes in the env variables
```
var environmentVariables = new Dictionary<string, string>()
{
["CRANK_PROCESS_ID"] = job.TrackedProcessId.ToString(),
["CRANK_WORKING_DIRECTORY"] = workingDirectory
};
```
and one cant use ENV variables when `process.StartInfo.UseShellExecute = true` which is required for admin rights (see `process.StartInfo.Verb = "runas";`).
=> fix: revert non-admin scripting usage

src/Microsoft.Crank.Jobs.PipeliningClient/HttpConnection.cs, src/Microsoft.Crank.Jobs.PipeliningClient/Program.cs, src/Microsoft.Crank.Jobs.PipeliningClient/pipelining.yml
fixing error
> [STDERR] Unhandled exception. System.Net.Sockets.SocketException (110): Connection timed out
[STDERR]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[STDERR]    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at Microsoft.Crank.Jobs.PipeliningClient.HttpConnection.ConnectAsync() in /tmp/benchmarks-agent/benchmarks-server-1/z2amnisn.51n/src/Microsoft.Crank.Jobs.PipeliningClient/HttpConnection.cs:line 97
[STDERR]    at Microsoft.Crank.Jobs.PipeliningClient.Program.DoWorkAsync() in /tmp/benchmarks-agent/benchmarks-server-1/z2amnisn.51n/src/Microsoft.Crank.Jobs.PipeliningClient/Prog …
=> fix: minor error handling improvement in pipelining client

docker/agent/Dockerfile, docker/agent/run.sh
run.sh was previously checking for the existence of strings (which will always cause the checks to return true) rather than the variable that was meant to be checked. Also fixed a minor casing mismatch that is causing a warning when building the crank-agent dockerfile.
Tested the changes locally and they work as expected. The dockerfile still builds, but without the warning, and the additional docker args are correctly passed when the vars exist.
=> Fix crank-agent run.sh variable existence check and minor casing mismatch fix.

src/Microsoft.Crank.AzureDevOpsWorker/JobPayload.cs, src/Microsoft.Crank.AzureDevOpsWorker/Microsoft.Crank.AzureDevOpsWorker.csproj, src/Microsoft.Crank.AzureDevOpsWorker/Program.cs, test/Microsoft.Crank.IntegrationTests/AzureWorkerTests.cs
This adds support for sending files over Azure Service Bus to the Azure Dev Ops Worker. Changes include adding a <string, string> dictionary for the files to the JobPayload, added the default usage of a temp directory to use as the working directory for these files (including cleanup), and added functionality to materialize base64 files from the JobPayload files dictionary to actual files.
=> Support job files in Azure Dev Ops Worker
